baseURL = 'https://y3un9.github.io'

title = '地铁武士'
author = 'y3un9'
languageCode = 'zh-CN'

enableRobotsTXT = true

enableEmoji = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.nav]]
    name = "Timeline"
    url = "/timeline"
    weight = 4
  [[menu.nav]]
    name = "Podcast"
    url = "/podcast"
    weight = 5

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = ""

  author = 'y3un9'

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = [""]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "地铁武士"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"

  github = 'https://github.com/y3un9'